#!/usr/bin/bash

menu_dir="$(dirname "$(readlink -f "$0")")/custom-menus"

if [ "$@" ]; then
  # get dir name and run the script in menus
  exec 1>&-
  "$menu_dir/$1"
else
  ls $menu_dir | grep -v '\.' | awk '{print $0 "\0icon\x1fmenu-editor"}'
fi

